version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'


  [[blocks.segments]]
    type = "battery"
    style = "plain"
    foreground = "red"
    background = "transparent"
    template = " {{ if not .Error }}{{ if or (gt .Percentage 99) (and (eq .State.String \"Discharging\") (le .Percentage 10)) }}{{ .Icon }}{{ .Percentage }}% |{{ end }}{{ end }}"

    [blocks.segments.properties]
      charged_icon = "󰁹 "
      discharging_icon = "󰂃 "
      not_charging_icon = "󰂃 "


  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = ' {{if not .Writable }}󰌾 {{ end }}{{ .Path }}'
    background = 'transparent'
    foreground = 'blue'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2


  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = ' on <p:white>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}[{{ .Working.String }}{{ .Staging.String }}]{{ end }}</>'
    background = 'transparent'
    foreground = 'p:grey'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true


  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:grey'
    template = " via <p:green> {{ .Full }}</>"

  [[blocks.segments]]
    type = 'java'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:grey'
    template = " via <p:red> {{ .Full }}</>"

  [[blocks.segments]]
    type = 'kotlin'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:grey'
    template = " via <p:orange><b>K</b> {{ .Full }}</>"

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = " via <p:yellow> {{ .Full }} ({{ if .Venv }}{{ .Venv }}{{ end }})</>"
    background = 'transparent'
    foreground = 'p:grey'


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    template = ' {{ .FormattedMs }} '
    background = 'transparent'
    foreground = 'yellow'
    Text = ''
    Duration = 0
    NameLength = 0


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
    template = '❯ '
    background = 'transparent'
    foreground = ''
    Text = ''
    Duration = 0
    NameLength = 0


[transient_prompt]
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
  template = '❯ '
  background = 'transparent'
  foreground = ''
  Text = ''
  Duration = 0
  NameLength = 0

[secondary_prompt]
  template = '❯❯ '
  background = 'transparent'
  foreground = 'magenta'
  Text = ''
  Duration = 0
  NameLength = 0

[palette]
  grey = '#cccccc'
  orange = '#ffaf00'
  red = '#ff5f5f'
  green = '#5fff5f'
  yellow = '#ffff5f'
  white = '#ffffff'
